// Writes the case-fold classes the pattern translators expand an any-case
// letter into: src/domain/javaCaseFolds.js and plaid-agent's
// core/java_case_folds.py. Run from plaid-igt: `node tools/caseFolds.mjs`.
//
// A class is a set of two or more code points that Unicode's simple case
// folding (CaseFolding.txt, statuses C and S) makes equal, which is what a
// JS RegExp with the `iu` flags compares by. So ı and İ are classes of their
// own, apart from i, as Turkic orthographies need (ruled 2026-10-02), while ſ
// folds with s, the Kelvin sign with k and ẞ with ß.
//
// The candidates for each code point are its case mappings (and theirs), and
// `iu` decides which of them fold together. The translators send the server
// explicit classes and no flag, so whatever this table says, the server, the
// browser and Python agree.

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const LAST_CASED = 0x1ffff;
const parent = new Map();
const find = (x) => {
  while (parent.has(x) && parent.get(x) !== x) x = parent.get(x);
  return x;
};
const union = (a, b) => {
  const [ra, rb] = [find(a), find(b)];
  if (ra !== rb) parent.set(Math.max(ra, rb), Math.min(ra, rb));
};

const single = (s) => {
  const cps = Array.from(s);
  return cps.length === 1 ? cps[0].codePointAt(0) : null;
};
const mappings = (cp) => {
  const c = String.fromCodePoint(cp);
  const out = new Set();
  for (const m of [c.toLowerCase(), c.toUpperCase()]) {
    const one = single(m);
    if (one == null) continue;
    out.add(one);
    for (const mm of [m.toLowerCase(), m.toUpperCase()]) {
      const two = single(mm);
      if (two != null) out.add(two);
    }
  }
  out.delete(cp);
  return out;
};

for (let cp = 0; cp <= LAST_CASED; cp++) {
  if (cp >= 0xd800 && cp <= 0xdfff) continue;
  const others = mappings(cp);
  if (!others.size) continue;
  const re = new RegExp(`^\\u{${cp.toString(16)}}$`, 'iu');
  for (const o of others) if (re.test(String.fromCodePoint(o))) union(cp, o);
}

const classes = new Map();
for (const cp of parent.keys()) {
  const root = find(cp);
  if (!classes.has(root)) classes.set(root, new Set([root]));
  classes.get(root).add(cp);
}
const sorted = [...classes.values()]
  .filter((c) => c.size > 1)
  .map((c) => [...c].sort((a, b) => a - b))
  .sort((a, b) => a[0] - b[0]);

const esc = (cp, lang) => {
  if (cp >= 0x20 && cp < 0x7f && cp !== 0x27 && cp !== 0x5c) return String.fromCodePoint(cp);
  if (cp <= 0xffff) return `\\u${cp.toString(16).padStart(4, '0')}`;
  return lang === 'py' ? `\\U${cp.toString(16).padStart(8, '0')}` : `\\u{${cp.toString(16)}}`;
};
const line = (cls, lang) => cls.map((cp) => esc(cp, lang)).join('');
const unicode = process.versions.unicode;

writeFileSync(
  resolve('src/domain/javaCaseFolds.js'),
  `// Generated by tools/caseFolds.mjs (Unicode ${unicode} simple case folding). Do not edit.\n` +
    `// Each string is one set of code points that fold together.\n` +
    `export default [\n${sorted.map((c) => `  '${line(c, 'js')}',`).join('\n')}\n];\n`,
);
writeFileSync(
  resolve('../plaid-agent/src/plaid_agent/core/java_case_folds.py'),
  `"""Generated by caseFolds.mjs (Unicode ${unicode} simple case folding). Do not edit.\n\n` +
    `Each string is one set of code points that fold together.\n"""\n\nFOLDS = [\n` +
    `${sorted.map((c) => `    '${line(c, 'py')}',`).join('\n')}\n]\n`,
);
console.log(`${sorted.length} classes`);
