// The server's regex engine (java.util.regex), for the clients' pattern
// translators (plaid-igt src/domain/javaRegex.js, plaid-agent
// core/java_regex.py). Run with `java tools/JavaRegex.java <mode>`.
//
//   folds js | folds py   prints the case-fold classes module: every set of
//                         two or more code points that share
//                         toLowerCase(toUpperCase(c)). The translators expand a
//                         case-insensitive letter into its class, so no engine
//                         folds case on its own.
//   oracle                reads lines `<pattern hex>\t<subject hex>` (UTF-8 as
//                         hex) and prints, per line, 1 when the pattern finds a
//                         match in the subject, 0 when not, E when the pattern
//                         does not compile. The same call the server's REGEXP
//                         function makes (Pattern.compile, no flags, find).

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;

public class JavaRegex {
  public static void main(String[] args) throws Exception {
    if (args.length >= 1 && args[0].equals("folds")) {
      folds(args.length > 1 ? args[1] : "js");
    } else if (args.length >= 1 && args[0].equals("oracle")) {
      oracle();
    } else {
      System.err.println("usage: JavaRegex folds js|py | oracle");
      System.exit(2);
    }
  }

  static void folds(String lang) {
    Map<Integer, List<Integer>> byKey = new TreeMap<>();
    for (int cp = 0; cp <= Character.MAX_CODE_POINT; cp++) {
      int key = Character.toLowerCase(Character.toUpperCase(cp));
      byKey.computeIfAbsent(key, k -> new ArrayList<>()).add(cp);
    }
    List<String> classes = new ArrayList<>();
    for (List<Integer> members : byKey.values()) {
      if (members.size() < 2) continue;
      StringBuilder sb = new StringBuilder();
      for (int cp : members) sb.append(escape(cp, lang));
      classes.add(sb.toString());
    }
    StringBuilder out = new StringBuilder();
    String version = System.getProperty("java.version");
    if (lang.equals("py")) {
      out.append("\"\"\"Generated by JavaRegex.java (`folds py`, Java ")
          .append(version)
          .append("). Do not edit.\n\nEach string is one set of code points that share\n")
          .append("Character.toLowerCase(Character.toUpperCase(c)).\n\"\"\"\n\nFOLDS = [\n");
      for (String c : classes) out.append("    '").append(c).append("',\n");
      out.append("]\n");
    } else {
      out.append("// Generated by tools/JavaRegex.java (`folds js`, Java ")
          .append(version)
          .append("). Do not edit.\n// Each string is one set of code points that share\n")
          .append("// Character.toLowerCase(Character.toUpperCase(c)).\n")
          .append("export default [\n");
      for (String c : classes) out.append("  '").append(c).append("',\n");
      out.append("];\n");
    }
    System.out.print(out);
  }

  static String escape(int cp, String lang) {
    if (cp >= 0x20 && cp < 0x7f && cp != '\'' && cp != '\\') return String.valueOf((char) cp);
    if (cp <= 0xffff) return String.format("\\u%04x", cp);
    if (lang.equals("py")) return String.format("\\U%08x", cp);
    return String.format("\\u{%x}", cp);
  }

  static void oracle() throws Exception {
    BufferedReader in =
        new BufferedReader(new InputStreamReader(System.in, StandardCharsets.UTF_8));
    PrintWriter out = new PrintWriter(System.out);
    String last = null;
    Pattern compiled = null;
    boolean bad = false;
    String line;
    while ((line = in.readLine()) != null) {
      int tab = line.indexOf('\t');
      String pattern = unhex(line.substring(0, tab));
      String subject = unhex(line.substring(tab + 1));
      if (!pattern.equals(last)) {
        last = pattern;
        try {
          compiled = Pattern.compile(pattern);
          bad = false;
        } catch (PatternSyntaxException e) {
          bad = true;
        }
      }
      out.println(bad ? "E" : compiled.matcher(subject).find() ? "1" : "0");
    }
    out.flush();
  }

  static String unhex(String h) {
    byte[] b = new byte[h.length() / 2];
    for (int i = 0; i < b.length; i++) b[i] = (byte) Integer.parseInt(h.substring(2 * i, 2 * i + 2), 16);
    return new String(b, StandardCharsets.UTF_8);
  }
}
