// Writes the two character classes the ignored-tokens rule reads, as code-point
// ranges: src/domain/punctuationClasses.js (igtConfig.js, import/align.js) and
// plaid-client-py's workflows/igt/punctuation_classes.py (ignored.py). Run from
// plaid-igt: `node tools/punctuationClasses.mjs`.
//
// The rule used to ask the runtime (`/[\p{P}\p{S}]/u`,
// `/\p{Extended_Pictographic}/u`), so its answer moved with the browser's or
// node's Unicode version: ★ is a pictograph in Unicode 16 and not in 17, and so
// it was a word in one browser and ignored in another, and Python, which had a
// table, disagreed with whichever node ran the comparison. One table, written
// here for both languages, answers the same everywhere. A word reference
// (`s3.w2`) counts words past the ignored tokens, so the agreement is what
// keeps those references valid.
//
// UNICODE is pinned. Moving it is a deliberate change: it changes which tokens
// existing documents ignore, and so the numbering of later words. Run this
// with a node whose `process.versions.unicode` is the new one, and set it here.

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const UNICODE = '16.0';
if (process.versions.unicode !== UNICODE) {
  console.error(
    `This node has Unicode ${process.versions.unicode}, and the tables are pinned to ${UNICODE}.`,
  );
  process.exit(1);
}

const ranges = (re) => {
  const out = [];
  for (let cp = 0; cp <= 0x10ffff; cp++) {
    if (!re.test(String.fromCodePoint(cp))) continue;
    const last = out[out.length - 1];
    if (last && last[1] === cp - 1) last[1] = cp;
    else out.push([cp, cp]);
  }
  return out;
};

const punct = ranges(/[\p{P}\p{S}]/u);
const picto = ranges(/\p{Extended_Pictographic}/u);

const hex = (cp, upper) => {
  const h = cp.toString(16).padStart(4, '0');
  return `0x${upper ? h.toUpperCase() : h}`;
};
const jsRanges = (rs) => rs.map(([a, b]) => `  [${hex(a)}, ${hex(b)}],`).join('\n');
const pyRanges = (rs) => {
  const rows = [];
  for (let i = 0; i < rs.length; i += 5) {
    rows.push(
      '    ' +
        rs
          .slice(i, i + 5)
          .map(([a, b]) => `(${hex(a, true)}, ${hex(b, true)}),`)
          .join(' '),
    );
  }
  return rows.join('\n');
};

writeFileSync(
  resolve('src/domain/punctuationClasses.js'),
  `// Generated by tools/punctuationClasses.mjs (Unicode ${UNICODE}). Do not edit.
// Inclusive code-point ranges, sorted. plaid-client-py's
// workflows/igt/punctuation_classes.py is written from the same run.

/** \`/[\\p{P}\\p{S}]/u\`: punctuation and symbols. */
export const PUNCT_OR_SYMBOL = [
${jsRanges(punct)}
];

/** \`/\\p{Extended_Pictographic}/u\`: emoji and the like. */
export const PICTOGRAPHIC = [
${jsRanges(picto)}
];

const inRanges = (ranges, c) => {
  const cp = c.codePointAt(0);
  if (cp === undefined) return false;
  let lo = 0;
  let hi = ranges.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (cp < ranges[mid][0]) hi = mid - 1;
    else if (cp > ranges[mid][1]) lo = mid + 1;
    else return true;
  }
  return false;
};

/** Is the first code point of \`c\` punctuation or a symbol? */
export const isPunctOrSymbol = (c) => inRanges(PUNCT_OR_SYMBOL, c);

/** Is the first code point of \`c\` a pictograph? */
export const isPictograph = (c) => inRanges(PICTOGRAPHIC, c);
`,
);
writeFileSync(
  resolve('../plaid-client-py/src/plaid_client/workflows/igt/punctuation_classes.py'),
  `"""Generated by plaid-igt/tools/punctuationClasses.mjs (Unicode ${UNICODE}). Do not edit.

Inclusive code-point ranges, sorted. plaid-igt's
src/domain/punctuationClasses.js is written from the same run.
"""

#: \`\`/[\\p{P}\\p{S}]/u\`\`: punctuation and symbols.
PUNCT_OR_SYMBOL = (
${pyRanges(punct)}
)

#: \`\`/\\p{Extended_Pictographic}/u\`\`: emoji and the like.
PICTOGRAPHIC = (
${pyRanges(picto)}
)
`,
);
console.log(`${punct.length} punctuation ranges, ${picto.length} pictograph ranges`);
