// Writes src/domain/spacelessScripts.js: the code points of the scripts
// written without spaces between words, as code-point ranges, which
// "Tokenize new text" (src/domain/newTextWords.js) reads to leave such text
// without words. The same run writes plaid-agent's
// plaid_agent/igt/spaceless_scripts.py, which the igt assistant's port of the
// rule (plaid_agent/igt/new_words.py) reads, so the two answer alike.
// Run from plaid-igt: `node tools/spacelessScripts.mjs`.
//
// A table, not runtime `\p{Script=...}`, so the answer does not move with the
// browser's Unicode version (see tools/punctuationClasses.mjs). UNICODE is
// pinned the same way: run with a node whose `process.versions.unicode` is it.

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const UNICODE = '16.0';
if (process.versions.unicode !== UNICODE) {
  console.error(
    `This node has Unicode ${process.versions.unicode}, and the table is pinned to ${UNICODE}.`,
  );
  process.exit(1);
}

// Scripts whose writing puts no space between words. By Script, not
// Script_Extensions, so shared punctuation (。, ・) stays out.
const SCRIPTS = [
  'Han',
  'Hiragana',
  'Katakana',
  'Bopomofo',
  'Yi',
  'Thai',
  'Lao',
  'Khmer',
  'Myanmar',
  'Tibetan',
  'Tai_Le',
  'New_Tai_Lue',
  'Tai_Tham',
  'Tai_Viet',
  'Balinese',
  'Javanese',
];

const re = new RegExp(`[${SCRIPTS.map((s) => `\\p{Script=${s}}`).join('')}]`, 'u');
const ranges = [];
for (let cp = 0; cp <= 0x10ffff; cp++) {
  if (!re.test(String.fromCodePoint(cp))) continue;
  const last = ranges[ranges.length - 1];
  if (last && last[1] === cp - 1) last[1] = cp;
  else ranges.push([cp, cp]);
}
const hex = (cp) => `0x${cp.toString(16).padStart(4, '0')}`;
const hexPy = (cp) => `0x${cp.toString(16).toUpperCase().padStart(4, '0')}`;
const pyRanges = (rs) => {
  const rows = [];
  for (let i = 0; i < rs.length; i += 5) {
    rows.push(
      '    ' +
        rs
          .slice(i, i + 5)
          .map(([a, b]) => `(${hexPy(a)}, ${hexPy(b)}),`)
          .join(' '),
    );
  }
  return rows.join('\n');
};

writeFileSync(
  resolve('src/domain/spacelessScripts.js'),
  `// Generated by tools/spacelessScripts.mjs (Unicode ${UNICODE}). Do not edit.
// Inclusive code-point ranges, sorted: the scripts written without spaces
// between words (${SCRIPTS.join(', ')}). plaid-agent's
// plaid_agent/igt/spaceless_scripts.py is written from the same run.

const SPACELESS_SCRIPTS = [
${ranges.map(([a, b]) => `  [${hex(a)}, ${hex(b)}],`).join('\n')}
];

/** Is the first code point of \`c\` in a script written without spaces? */
export const isSpacelessScript = (c) => {
  const cp = c.codePointAt(0);
  if (cp === undefined) return false;
  let lo = 0;
  let hi = SPACELESS_SCRIPTS.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (cp < SPACELESS_SCRIPTS[mid][0]) hi = mid - 1;
    else if (cp > SPACELESS_SCRIPTS[mid][1]) lo = mid + 1;
    else return true;
  }
  return false;
};
`,
);
writeFileSync(
  resolve('../plaid-agent/src/plaid_agent/igt/spaceless_scripts.py'),
  `"""Generated by plaid-igt/tools/spacelessScripts.mjs (Unicode ${UNICODE}). Do not edit.

Inclusive code-point ranges, sorted: the scripts written without spaces
between words (${SCRIPTS.join(', ')}). plaid-igt's
src/domain/spacelessScripts.js is written from the same run.
"""

SPACELESS_SCRIPTS = (
${pyRanges(ranges)}
)
`,
);
console.log(`${ranges.length} ranges`);
