= Plaid Manual
:lang: en
:encoding: UTF-8
:doctype: book
:toc: left
:toclevels: 3
:sectlinks:
:sectanchors:
:leveloffset: 1
:sectnums:
:hide-uri-scheme: 1
:source-highlighter: coderay

= Development

* `clojure -X:dev`: start development server by typing `(start)`. See <http://localhost:8085>
* `clojure -M:test`: run tests
* `clojure -M:outdated`: find outdated dependencies
* `clojure -X:uberjar`: compile to a single `.jar` for production
* `clojure -M:gen target/openapi.json target/clients/client.py py`: generate Python client
* `clojure -M:gen target/openapi.json target/clients/client.js js`: generate JavaScript client
* `clojure -M:nrepl`: start nREPL server (for Clojure MCP)

== OpenAPI Support
* See playground at <http://localhost:8085/api/v1/docs/index.html#/>
* See JSON at <http://localhost:8085/api/v1/openapi.json>

== XTDB Inspector
Make sure that the environment variable `XTDB_INSPECTOR_URI_PREFIX` is set to `/_inspector` if you want to use the web UI to inspect the database.

[,bash]
----
export XTDB_INSPECTOR_URI_PREFIX=/_inspector
----

On Windows, use the snippet below, then restart commandline/powershell! Value is only accessible in future cmd/pwsh instances.

[,cmd]
----
setx XTDB_INSPECTOR_URI_PREFIX "/_inspector"
----

Inspector will be visible at <http://localhost:8085/_inspector/attr>.