(ns plaid.server.services-extract-test
  "Pins the overwrite-if-unmodified contract of the bundled-services
  extraction planner (pure fn; the IO wrapper is exercised by the release
  workflow's jar smoke test). Requiring this ns registers the
  services-extract defstate JVM-wide, which is safe: its :start is a
  guaranteed no-op when the classpath carries no services/manifest.edn
  (true for every dev/test JVM — the manifest is generated by CI)."
  (:require [clojure.test :refer [deftest is testing]]
            [plaid.server.services-extract :as sx]))

(defn- action-for [actions file]
  (first (filter #(= file (:file %)) actions)))

(deftest plan-extraction-contract
  (let [shipped {"a.py" "h2" "b.py" "h1"}]
    (testing "absent files are written"
      (let [{:keys [actions]} (sx/plan-extraction shipped {} {})]
        (is (= {:file "a.py" :action :write :reason :absent} (action-for actions "a.py")))
        (is (= {:file "b.py" :action :write :reason :absent} (action-for actions "b.py")))))
    (testing "unmodified current copies are left as-is"
      (let [{:keys [actions]} (sx/plan-extraction shipped {"a.py" "h2"} {"a.py" ["h2"]})]
        (is (= :skip (:action (action-for actions "a.py"))))
        (is (= :unmodified (:reason (action-for actions "a.py"))))))
    (testing "an unmodified STALE copy (matches a previously-shipped hash) is updated"
      (let [{:keys [actions]} (sx/plan-extraction shipped {"a.py" "h1"} {"a.py" ["h1"]})]
        (is (= {:file "a.py" :action :write :reason :update} (action-for actions "a.py")))))
    (testing "a locally-edited file is never clobbered"
      (let [{:keys [actions]} (sx/plan-extraction shipped {"a.py" "deadbeef"} {"a.py" ["h1"]})]
        (is (= {:file "a.py" :action :skip :reason :local-edit} (action-for actions "a.py")))))
    (testing "a file whose hash was never recorded counts as a local edit (fail-safe)"
      (let [{:keys [actions]} (sx/plan-extraction shipped {"a.py" "h1"} {})]
        (is (= :local-edit (:reason (action-for actions "a.py"))))))))

(deftest plan-extraction-history-accumulates-shipped-hashes
  (testing "every shipped hash is appended once, preserving prior history"
    (let [{:keys [history]} (sx/plan-extraction {"a.py" "h2"} {"a.py" "deadbeef"} {"a.py" ["h1"]})]
      (is (= {"a.py" ["h1" "h2"]} history)))
    (let [{:keys [history]} (sx/plan-extraction {"a.py" "h2"} {"a.py" "h2"} {"a.py" ["h1" "h2"]})]
      (is (= {"a.py" ["h1" "h2"]} history) "re-shipping the same hash doesn't duplicate")))
  (testing "history records the shipped hash even when the write is refused —
            so reverting a local edit by hand makes the NEXT boot recognize it"
    (let [{:keys [history]} (sx/plan-extraction {"a.py" "h3"} {"a.py" "deadbeef"} {"a.py" ["h1"]})]
      (is (= ["h1" "h3"] (get history "a.py"))))))
