(ns plaid.server.services-extract
  "First-run extraction of the official Python services bundled into the jar.

  The release build copies each app's `services/*.py` into the jar under
  `services/`, alongside a generated `services/manifest.edn` mapping filename
  -> sha256 (the manifest is how we enumerate — a jar \"directory\" can't be
  listed portably). On boot we extract them into a `services/` folder sibling
  to the data dir, with OVERWRITE-IF-UNMODIFIED semantics:

  - absent on disk            -> write
  - disk == current shipped   -> no-op
  - disk == some PREVIOUSLY shipped version -> overwrite (it's an unmodified
    stale copy; log at info)
  - anything else             -> leave alone + warn (the operator edited it)

  \"Previously shipped\" is tracked in `<data-dir>/services-manifest.edn`:
  {filename [hash1 ... hashN]} — the full history of shipped hashes per file,
  appended on every boot that ships a new version. Files are never deleted.

  Dev/test JVMs have no `services/manifest.edn` resource (it's generated by
  CI), so the whole thing no-ops outside a release jar. This ns must be
  required ONLY from `plaid.server.main` — requiring it from a test ns would
  register the defstate JVM-wide and perturb the full-mount lifecycle tests."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [mount.core :refer [defstate]]
            [plaid.server.config :refer [config]]
            [taoensso.timbre :as log])
  (:import [java.security MessageDigest]))

(defn- sha256-hex
  ^String [^bytes data]
  (let [d (.digest (MessageDigest/getInstance "SHA-256") data)]
    (apply str (map #(format "%02x" %) d))))

(defn plan-extraction
  "Pure planning: decide per shipped file what to do.

  - shipped:     {filename current-shipped-hash}
  - disk-hashes: {filename hash-or-nil} (nil = absent)
  - history:     {filename [previously-shipped hashes]} (state manifest)

  Returns {:actions [{:file :action :reason}] :history <updated history>}.
  Actions: :write (reason :absent or :update) / :skip (reason :unmodified or
  :local-edit). The updated history appends each file's current shipped hash
  (it has now been shipped, regardless of whether we wrote)."
  [shipped disk-hashes history]
  (let [actions
        (vec
         (for [[file shipped-hash] (sort-by key shipped)]
           (let [disk-hash (get disk-hashes file)
                 shipped-before (set (get history file []))]
             (cond
               (nil? disk-hash) {:file file :action :write :reason :absent}
               (= disk-hash shipped-hash) {:file file :action :skip :reason :unmodified}
               (shipped-before disk-hash) {:file file :action :write :reason :update}
               :else {:file file :action :skip :reason :local-edit}))))
        history' (reduce (fn [h [file shipped-hash]]
                           (let [hashes (vec (get h file []))]
                             (if (some #{shipped-hash} hashes)
                               (assoc h file hashes)
                               (assoc h file (conj hashes shipped-hash)))))
                         history
                         shipped)]
    {:actions actions :history history'}))

(defn- read-edn-file
  "EDN from `f` if it exists and parses, else nil (corrupt state manifest just
  means we fall back to fresh history — worst case locally-stale files are
  treated as local edits and left alone)."
  [^java.io.File f]
  (when (.exists f)
    (try (edn/read-string (slurp f))
         (catch Exception e
           (log/warn e "Unreadable manifest at" (.getPath f) "— starting fresh")
           nil))))

(defn- resource-bytes ^bytes [path]
  (when-let [res (io/resource path)]
    (with-open [in (io/input-stream res)
                out (java.io.ByteArrayOutputStream.)]
      (io/copy in out)
      (.toByteArray out))))

(defn- data-dir
  "The data directory, derived from the configured SQLite path (its parent),
  same as the rest of the default `data/` layout. Falls back to ./data."
  [cfg]
  (let [db-path (get-in cfg [:plaid.server.sql/config :main-db-path])
        parent (some-> db-path io/file .getParentFile)]
    (or parent (io/file "data"))))

(defn extract-bundled-services!
  "Extract bundled services per `plan-extraction`. No-op when the jar carries
  no services manifest (dev/test). Returns the action list (for logging /
  tests), or nil when skipped."
  [cfg]
  (if-let [manifest-res (io/resource "services/manifest.edn")]
    (let [shipped (edn/read-string (slurp manifest-res))
          ddir (data-dir cfg)
          services-dir (io/file (or (.getParentFile ^java.io.File ddir) (io/file ".")) "services")
          state-file (io/file ddir "services-manifest.edn")
          ;; Hash the actual bundled bytes rather than trusting the built
          ;; manifest blindly; warn on drift but prefer the real content.
          shipped-bytes (into {} (for [[file _] shipped]
                                   [file (resource-bytes (str "services/" file))]))
          shipped-hashes (into {} (for [[file declared] shipped
                                        :let [data (get shipped-bytes file)]
                                        :when data]
                                    (let [actual (sha256-hex data)]
                                      (when (not= actual declared)
                                        (log/warn "Bundled hash mismatch for" file "— using actual content hash"))
                                      [file actual])))
          disk-hashes (into {} (for [[file _] shipped-hashes
                                     :let [f (io/file services-dir file)]]
                                 [file (when (.exists f)
                                         (sha256-hex (with-open [in (io/input-stream f)
                                                                 out (java.io.ByteArrayOutputStream.)]
                                                       (io/copy in out)
                                                       (.toByteArray out))))]))
          history (or (read-edn-file state-file) {})
          {:keys [actions history]} (plan-extraction shipped-hashes disk-hashes history)]
      (.mkdirs services-dir)
      (doseq [{:keys [file action reason]} actions]
        (case action
          :write (do (with-open [out (io/output-stream (io/file services-dir file))]
                       (.write out ^bytes (get shipped-bytes file)))
                     (log/info (if (= reason :absent)
                                 (str "Extracted bundled service services/" file)
                                 (str "Updated bundled service services/" file " to the shipped version"))))
          :skip (when (= reason :local-edit)
                  (log/warn (str "services/" file " is locally modified; leaving it alone"
                                 " (delete it to get the shipped version on next boot)")))))
      (.mkdirs ddir)
      (spit state-file (pr-str (into (sorted-map) history)))
      actions)
    (do (log/debug "No bundled services manifest on the classpath; skipping extraction")
        nil)))

(defstate services-extract
  :start (extract-bundled-services! config))
