-- Drop everything the baseline created. CASCADE because the tables are a
-- dense FK graph and the drop order below is not topologically sorted.
DROP TABLE IF EXISTS data_migrations CASCADE;
--;;
DROP TABLE IF EXISTS seen_services CASCADE;
--;;
DROP TABLE IF EXISTS audit_retention CASCADE;
--;;
DROP TABLE IF EXISTS audit_writes CASCADE;
--;;
DROP TABLE IF EXISTS operations CASCADE;
--;;
DROP TABLE IF EXISTS operation_groups CASCADE;
--;;
DROP TABLE IF EXISTS invites CASCADE;
--;;
DROP TABLE IF EXISTS api_tokens CASCADE;
--;;
DROP TABLE IF EXISTS comments CASCADE;
--;;
DROP TABLE IF EXISTS entity_metadata CASCADE;
--;;
DROP TABLE IF EXISTS vocab_link_tokens CASCADE;
--;;
DROP TABLE IF EXISTS vocab_links CASCADE;
--;;
DROP TABLE IF EXISTS vocab_items CASCADE;
--;;
DROP TABLE IF EXISTS project_vocabs CASCADE;
--;;
DROP TABLE IF EXISTS vocab_maintainers CASCADE;
--;;
DROP TABLE IF EXISTS vocab_layers CASCADE;
--;;
DROP TABLE IF EXISTS relations CASCADE;
--;;
DROP TABLE IF EXISTS span_tokens CASCADE;
--;;
DROP TABLE IF EXISTS spans CASCADE;
--;;
DROP TABLE IF EXISTS tokens CASCADE;
--;;
DROP TABLE IF EXISTS texts CASCADE;
--;;
DROP TABLE IF EXISTS relation_layers CASCADE;
--;;
DROP TABLE IF EXISTS span_layers CASCADE;
--;;
DROP TABLE IF EXISTS token_layers CASCADE;
--;;
DROP TABLE IF EXISTS text_layers CASCADE;
--;;
DROP TABLE IF EXISTS documents CASCADE;
--;;
DROP TABLE IF EXISTS project_users CASCADE;
--;;
DROP TABLE IF EXISTS projects CASCADE;
--;;
DROP TABLE IF EXISTS user_data CASCADE;
--;;
DROP TABLE IF EXISTS user_avatars CASCADE;
--;;
DROP TABLE IF EXISTS users CASCADE;
