DROP TABLE IF EXISTS audit_writes;
--;;
DROP TABLE IF EXISTS operations;
--;;
DROP TABLE IF EXISTS entity_metadata;
--;;
DROP TABLE IF EXISTS vocab_link_tokens;
--;;
DROP TABLE IF EXISTS vocab_links;
--;;
DROP TABLE IF EXISTS vocab_items;
--;;
DROP TABLE IF EXISTS project_vocabs;
--;;
DROP TABLE IF EXISTS vocab_maintainers;
--;;
DROP TABLE IF EXISTS vocab_layers;
--;;
DROP TABLE IF EXISTS relations;
--;;
DROP TABLE IF EXISTS span_tokens;
--;;
DROP TABLE IF EXISTS spans;
--;;
DROP TABLE IF EXISTS tokens;
--;;
DROP TABLE IF EXISTS texts;
--;;
DROP TABLE IF EXISTS relation_layers;
--;;
DROP TABLE IF EXISTS span_layers;
--;;
DROP TABLE IF EXISTS token_layers;
--;;
DROP TABLE IF EXISTS text_layers;
--;;
DROP TABLE IF EXISTS documents;
--;;
DROP TABLE IF EXISTS project_users;
--;;
DROP TABLE IF EXISTS projects;
--;;
DROP TABLE IF EXISTS users;
