"""Word documents for generated outputs: dig4el's lesson DOCX, the localized headings
copied verbatim from ``libs/output_generation_utils.py`` (Sebastien Christian, AGPL-3.0)."""

from __future__ import annotations

import re
import unicodedata
from io import BytesIO

from docx import Document

_BAD_XML_CHARS_RE = re.compile("[\x00-\x08\x0b\x0c\x0e-\x1f]")


def safe_text(value: object) -> str:
    """XML-safe, non-None, length-capped text."""
    if value is None:
        return ""
    text = _BAD_XML_CHARS_RE.sub("", str(value))
    return unicodedata.normalize("NFC", text)[:32760]


def lesson_docx(content: dict, indi_language: str, readers_language: str) -> BytesIO:
    loc = {
        "English": {
            "introduction": "Introduction",
            "for example": "For example",
            "in conclusion": "In Conclusion",
            "more_examples": "More examples",
            "learning_the_x_language_grammar": "Learning the X language grammar"
        },
        "Bislama": {
            "introduction": "Introdaksen",
            "for example": "Foa eksampol",
            "in conclusion": "Long fin",
            "more_examples": "Mo eksampol",
            "learning_the_x_language_grammar": "Lernim graema blong lanwis X"
        },
        "French": {
            "introduction": "Introduction",
            "for example": "Par exemple",
            "in conclusion": "En conclusion",
            "more_examples": "Plus d'exemples",
            "learning_the_x_language_grammar": "Apprentissage de la grammaire de la langue X"
        },
        "Japanese": {
            "introduction": "はじめに",
            "for example": "例えば",
            "in conclusion": "結論として",
            "more_examples": "さらに例",
            "learning_the_x_language_grammar": "X言語の文法を学ぶ"
        },
        "Swedish": {
            "introduction": "Introduktion",
            "for example": "Till exempel",
            "in conclusion": "Sammanfattningsvis",
            "more_examples": "Fler exempel",
            "learning_the_x_language_grammar": "Att lära sig X-språkets grammatik"
        }
    }
    locit = loc.get(readers_language, loc["English"])

    document = Document()
    document.add_paragraph("Generated by DIG4EL " + content.get("date", "unknown"))
    document.add_heading(safe_text(content["title"]), level=0)
    document.add_paragraph(safe_text("  "))
    document.add_paragraph(safe_text(content["introduction"]))

    for section in content["sections"]:
        document.add_heading(safe_text(section["focus"]), level=2)
        if isinstance(section["description"], str):
            document.add_paragraph(safe_text(section["description"]))
        elif isinstance(section["description"], dict):
            document.add_paragraph(safe_text(section["description"].get("description", "...")))
        document.add_paragraph(safe_text(locit["for example"] + ": "))
        examples = section.get("example") or section.get("examples") or []
        if isinstance(examples, dict):
            examples = [examples]
        for n, example in enumerate(examples, start=1):
            pex = document.add_paragraph(safe_text(" "), "Normal")
            pex.add_run(safe_text(f"{n}) "))
            pex.add_run(safe_text(example["target_sentence"]), style="Strong")
            document.add_paragraph(safe_text(example["source_sentence"]), "Normal")
            document.add_paragraph(safe_text(example["description"]))

    if content.get("conclusion"):
        document.add_heading(safe_text(locit["in conclusion"]), level=1)
        document.add_paragraph(safe_text(" "))
        document.add_paragraph(safe_text(content["conclusion"]))

    if content.get("translation_drills"):
        document.add_heading(safe_text(locit["more_examples"] + ": "))
        document.add_paragraph(safe_text(" "))
        for s in content["translation_drills"]:
            aex = document.add_paragraph(safe_text(" "), style="List Bullet")
            aex.add_run(safe_text(s["target"]), style="Strong")
            document.add_paragraph(safe_text(f'({s["source"]})'), "Normal")

    document.add_heading(safe_text("Sources"), level=1)
    sources = content.get("sources", {})
    for key, heading in (("documents", "Documents: "), ("cqs", "Conversational Questionnaires: "),
                         ("pairs", "Sentence pairs: ")):
        if sources.get(key):
            document.add_heading(safe_text(heading), level=2)
            for d in sources[key]:
                document.add_paragraph(safe_text(d), style="List Bullet")
    buf = BytesIO()
    document.save(buf)
    buf.seek(0)
    return buf
