"""dig4el's transcription workbook and Word exports, and the workbook import
(``libs/output_generation_utils.py``, Sebastien Christian, AGPL-3.0), copied verbatim
with imports rewired: an Excel template of a questionnaire for field work, the same as
a Word document, the parser that turns a filled workbook back into a recording, and a
Word document of glossed sentences."""

from __future__ import annotations

import re
import time
import unicodedata
from collections.abc import Mapping
from io import BytesIO
from typing import Any, Dict, Optional, Union

from docx import Document
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from .docx_export import safe_text
from .inference.kg import build_super_gloss
from .inference.tokenizer import custom_split

DEFAULT_DELIMITERS = [" ", ".", ",", ";", ":", "!", "?", "…"]
STATS_DELIMITERS = [".", ",", ":", ";", "?", "!", "(", ")", " "]  # dig4el's stats.custom_split default


def normalize_text(text: str) -> str:
    return unicodedata.normalize("NFC", text)


def normalize_user_strings(obj):
    if isinstance(obj, str):
        return normalize_text(obj)
    if isinstance(obj, Mapping):
        return {k: normalize_user_strings(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [normalize_user_strings(v) for v in obj]
    if isinstance(obj, tuple):
        return tuple(normalize_user_strings(v) for v in obj)
    return obj


def _norm(s: Any) -> str:
    """Best-effort normalize to a clean string."""
    if s is None:
        return ""
    s = str(s)
    # preserve user content; just trim
    return s.strip()


def _read_info_kv(ws) -> Dict[str, str]:
    """
    Reads Info sheet key/value pairs that were written as:
      A5..: key, B5..: value
    """
    kv: Dict[str, str] = {}
    for row in ws.iter_rows(min_row=1, max_col=2):
        k = _norm(row[0].value)
        v = _norm(row[1].value) if len(row) > 1 else ""
        if k:
            kv[k] = v
    return kv


def _extract_uid_from_info(ws_info) -> str:
    """
    Builder wrote:
      A3 = f"“UID: {cq.get('uid', '')}”"
    so parse whatever is after UID:
    """
    a3 = _norm(ws_info["A3"].value)
    if not a3:
        return ""
    return a3[4:]


def cq_translation_from_transcription_xlsx(
    xlsx: Union[str, bytes, BytesIO],
    *,
    default_target_language: str = "target language",
) -> Dict[str, Any]:
    """
    Parse a completed CQ transcription workbook (generated by generate_transcription_xlsx)
    and return a CQ translation JSON dict.

    Parameters
    ----------
    xlsx:
        Path to .xlsx OR bytes OR BytesIO.

    default_target_language:
        Used if the Info sheet didn't specify a target language.
    """
    if isinstance(xlsx, (bytes, bytearray)):
        xlsx = BytesIO(xlsx)

    wb = load_workbook(xlsx, data_only=True)

    if "Info" not in wb.sheetnames:
        raise ValueError("Missing required sheet: 'Info'")
    if "Transcription" not in wb.sheetnames:
        raise ValueError("Missing required sheet: 'Transcription'")

    ws_info = wb["Info"]
    ws_t = wb["Transcription"]

    info_kv = _read_info_kv(ws_info)

    target_language = _norm(info_kv.get("Target language", "")) or default_target_language
    pivot_language = _norm(info_kv.get("Pivot language (if any)", "")) or "English"

    transcription_made_by = _norm(info_kv.get("Transcription made by", ""))
    provided_by_key = f"Content provided by"
    content_provided_by = _norm(info_kv.get(provided_by_key, ""))
    recording_date = _norm(info_kv.get("Recording date", ""))

    location = _norm(info_kv.get("Recording location", "")) or "unknown"

    cq_uid = _extract_uid_from_info(ws_info)

    # ---- Parse Transcription sheet ----
    # Header in row 1:
    # ["Index","English","Pivot (if not English)",f"Sentence in {target_language}",
    #  "Literal English Back-Translation","Concept item","Word(s) contributing...","Notes"]
    data: Dict[str, Any] = {}

    current_index: Optional[str] = None
    segment_number = 0
    segment_number_str = "0"

    # Iterate rows after header
    for r in ws_t.iter_rows(min_row=2, values_only=True):
        idx = _norm(r[0])
        english = _norm(r[1])
        pivot = _norm(r[2])
        target_sentence = _norm(r[3])
        lebt = _norm(r[4])
        concept_item = _norm(r[5])
        concept_words = _norm(r[6])
        notes = _norm(r[7])

        if idx:
            current_index = idx
            segment_number += 1
            segment_number_str = str(segment_number)
        #
        # if not current_index:
        #     # no index yet => ignore stray rows
        #     continue
        if current_index:
            if segment_number_str not in data:
                data[segment_number_str] = {
                    "legacy index": current_index,
                    "cq": english,
                    "alternate_pivot": pivot,
                    "translation": target_sentence,
                    "concept_words": {},
                    "lebt": "",
                    "comment": ""
                }

            entry = data[segment_number_str]

            # Update turn-level fields if present on this row
            if english:
                entry["cq"] = english
            if pivot:
                entry["alternate_pivot"] = pivot
            if target_sentence:
                entry["translation"] = target_sentence

            if lebt:
                entry["lebt"] = lebt
            if notes:
                entry["comment"] = notes

            # Concept mapping row
            if concept_item:
                # concept_words in the form word1...word2...etc
                if concept_words:
                    # print("idx: {}".format(idx))
                    # print("entry: {}".format(entry))
                    # print("translation: {}".format(entry["translation"]))
                    # print("concept_item: {}".format(concept_item))
                    # print("concept_words: {}".format(concept_words))
                    # cleaning and validation (valid if in the target sentence)
                    words_in_sentence = custom_split(entry["translation"], STATS_DELIMITERS)
                    # print("words_in_sentence: {}".format(words_in_sentence))
                    wcl_tmp = concept_words.split("...")
                    wcl = [w.lower().strip() for w in wcl_tmp]
                    validated_wcl = [w for w in wcl if w in words_in_sentence]
                    # print("validated_wcl: {}".format(validated_wcl))
                    validated_concept_words = "...".join(validated_wcl)
                    entry["concept_words"][concept_item] = validated_concept_words
                    # print("validated_concept_words: {}".format(validated_concept_words))
                    # print("final entry: {}".format(entry))
                else:
                    entry["concept_words"][concept_item] = ""


    # ---- Build final JSON ----
    interviewer = transcription_made_by or ""
    interviewee = content_provided_by or ""

    out = {
        "target language": target_language,
        "delimiters": DEFAULT_DELIMITERS,
        "pivot language": pivot_language,
        "cq_uid": cq_uid,
        "data": data,
        "interviewer": interviewer,
        "interviewee": interviewee,
        "location": location,
        "date": recording_date,
        "recording_uid": str(int(time.time())),
        "owner name": " and ".join([x for x in [interviewee, interviewer] if x]) or "",
        "owner orcid": "",
        "authorization": "accessed read-only by anyone via DIG4EL tools",

    }

    return out

# ======================================================================================


def generate_transcription_xlsx(cq, target_language, pivot_language):
    """
    Create an Excel workbook template for CQ transcription/annotation.

    Sheets:
      - Info: questionnaire metadata + contributor fields
      - Dialog: the English dialog, one row per turn
      - Transcription: normalized "long" format, one row per (turn, concept_item)
          concept_item includes: Intent:..., Type of predicate:..., and each concept in content["concept"].
    Returns: BytesIO positioned at 0.
    """
    cq = normalize_user_strings(cq)
    target_language = normalize_text(target_language)
    pivot_language = normalize_text(pivot_language)

    if target_language in ["English", ""]:
        target_language = "target language"

    wb = Workbook()

    # ---------- helpers ----------
    header_fill = PatternFill("solid", fgColor="EDEDED")
    bold = Font(bold=True)
    wrap = Alignment(wrap_text=True, vertical="top")
    top = Alignment(vertical="top")

    def set_col_width(ws, widths):
        for col_idx, width in enumerate(widths, start=1):
            ws.column_dimensions[get_column_letter(col_idx)].width = width

    def make_header(ws, row_idx, headers):
        for c, h in enumerate(headers, start=1):
            cell = ws.cell(row=row_idx, column=c, value=h)
            cell.font = bold
            cell.fill = header_fill
            cell.alignment = Alignment(wrap_text=True, vertical="center")
        ws.freeze_panes = ws[f"A{row_idx+1}"]

    # ---------- Sheet 1: Info ----------
    ws_info = wb.active
    ws_info.title = "Info"

    ws_info["A1"] = "Conversational Questionnaire"
    ws_info["A1"].font = Font(bold=True, size=20)
    ws_info["A2"] = f"“{cq.get('title','')}”"
    ws_info["A2"].font = Font(bold=True, size=14)
    ws_info["A3"] = "UID:{}".format(cq.get('uid', ''))
    ws_info["A3"].font = Font(bold=True, size=14)

    rows = [
        ("Target language", "" if target_language == "target language" else target_language),
        ("Pivot language (if any)", "" if pivot_language in ["English", ""] else pivot_language),
        ("Transcription made by", ""),
        (f"Content provided by", ""),
        ("Recording location", ""),
        ("Recording date", "")
    ]
    start = 5
    ws_info[f"A{start-1}"] = "Information"
    ws_info[f"A{start-1}"].font = Font(bold=True, size=14)

    for i, (k, v) in enumerate(rows):
        r = start + i
        ws_info[f"A{r}"] = k
        ws_info[f"A{r}"].font = bold
        ws_info[f"A{r}"].alignment = top
        ws_info[f"B{r}"] = v
        ws_info[f"B{r}"].alignment = top

    ws_info["A12"] = "Full dialog context (English)"
    ws_info["A12"].font = bold
    ws_info["A13"] = cq.get("context", "")
    ws_info["A13"].alignment = wrap
    ws_info.merge_cells("A13:D18")

    set_col_width(ws_info, [34, 50, 18, 18])

    # ---------- Sheet 2: Dialog ----------
    ws_dialog = wb.create_sheet("Dialog")
    speaker_a = cq.get("speakers", {}).get("A", {}).get("name", "Speaker A")
    speaker_b = cq.get("speakers", {}).get("B", {}).get("name", "Speaker B")

    make_header(ws_dialog, 1, [
        "Index",
        "Speaker",
        speaker_a,
        speaker_b,
    ])

    dialog = cq.get("dialog", {})
    dialog_length = len(dialog)

    for idx in range(1, dialog_length + 1):
        content = dialog.get(str(idx), {})
        legacy = content.get("legacy index", "")
        shown_index = legacy if legacy != "" else str(idx)

        speaker = content.get("speaker", "")
        text = content.get("text", "")

        row = [
            shown_index,
            speaker,
            text if speaker == "A" else "",
            text if speaker == "B" else "",
        ]
        ws_dialog.append(row)

    # formatting
    set_col_width(ws_dialog, [10, 10, 60, 60])
    for row in ws_dialog.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = wrap

    # ---------- Sheet 3: Transcription (long format) ----------
    ws_t = wb.create_sheet("Transcription")

    make_header(ws_t, 1, [
        "Index",
        "English",
        "Pivot (if not English)",
        f"Sentence in {target_language}",
        "Literal English Back-Translation",
        "Concept item",
        "Word(s) contributing to this concept item (separated by ... when multiple)",
        "Notes",
    ])

    for idx in range(1, dialog_length + 1):
        content = dialog.get(str(idx), {})
        legacy = content.get("legacy index", "")
        shown_index = legacy if legacy != "" else str(idx)

        english_turn = content.get("text", "")

        # Each "concept item" becomes its own row => easy to query later.
        concept_items = []

        if content.get("intent", []) != []:
            concept_items.append(f'Intent: {"+".join(content["intent"])}')

        for c in content.get("concept", []) or []:
            concept_items.append(str(c))

        # Always create at least one row per turn, even if no concept items exist.
        if not concept_items:
            concept_items = [""]
        first = True
        for concept_item in concept_items:
            if first:
                ws_t.append([
                    shown_index,
                    english_turn,
                    "",          # pivot
                    "",          # target sentence
                    "",          # LEBT
                    concept_item,
                    "",          # word(s) mapping
                    "",          # notes
                ])
                first = False
            else:
                ws_t.append([
                    "",  # don't repeat index
                    "",  # don't repeat English
                    "",  # pivot
                    "",  # target sentence
                    "",  # LEBT
                    concept_item,
                    "",  # word(s) mapping
                    "",  # notes
                ])

    set_col_width(ws_t, [10, 12, 45, 30, 45, 40, 45, 30])
    for row in ws_t.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = wrap

    # ---------- Save to BytesIO ----------
    xlsx_buffer = BytesIO()
    wb.save(xlsx_buffer)
    xlsx_buffer.seek(0)
    return xlsx_buffer


def generate_transcription_doc(cq, target_language, pivot_language):
    cq = normalize_user_strings(cq)
    target_language = normalize_text(target_language)
    pivot_language = normalize_text(pivot_language)
    if target_language in ["English", ""]:
        target_language = "target language"

    document = Document()
    document.add_heading(safe_text('Conversational Questionnaire'), 0)
    document.add_heading(safe_text(f'"{cq["title"]}"'), 0)
    document.add_heading(safe_text("Information"), 1)
    table = document.add_table(rows=5, cols=2, style="Light Grid")  # Fixed column count
    row_cells0 = table.rows[0].cells
    row_cells0[0].text = safe_text("Target language")
    if target_language != "target language":
        row_cells0[1].text = safe_text(target_language)
    row_cells1 = table.rows[1].cells
    row_cells1[0].text = safe_text("Transcription made by")
    row_cells2 = table.rows[2].cells
    row_cells2[0].text = safe_text(f"Content in {target_language} provided by")
    row_cells3 = table.rows[3].cells
    row_cells3[0].text = safe_text("Location")
    row_cells4 = table.rows[4].cells
    row_cells4[0].text = safe_text("Date")

    document.add_page_break()

    document.add_heading(safe_text("Full dialog in English"), 1)
    document.add_paragraph(safe_text(cq["context"]))
    dialog_table = document.add_table(rows=1, cols=3, style="Table Grid")  # Fixed column count
    hdr_cells = dialog_table.rows[0].cells
    hdr_cells[0].text = safe_text("Index")
    hdr_cells[1].text = safe_text(cq["speakers"]["A"]["name"])
    hdr_cells[2].text = safe_text(cq["speakers"]["B"]["name"])
    dialog_length = len(cq["dialog"])
    for index in range(1, dialog_length + 1):
        content = cq["dialog"][str(index)]
        row_cells = dialog_table.add_row().cells
        if content.get("legacy index", "") != "":
            i = content["legacy index"]
        else:
            i = str(index)
        row_cells[0].text = safe_text(i)
        if content["speaker"] == "A":
            row_cells[1].text = safe_text(content["text"])
            row_cells[2].text = safe_text("")
        elif content["speaker"] == "B":
            row_cells[1].text = safe_text("")
            row_cells[2].text = safe_text(content["text"])

    document.add_page_break()

    document.add_heading(safe_text("Transcription"), 1)

    for index in range(1, dialog_length + 1):
        content = cq["dialog"][str(index)]
        if content.get("legacy index", "") != "":
            i = content["legacy index"]
        else:
            i = str(index)
        document.add_paragraph(safe_text(""))
        document.add_heading(safe_text(f'{i}: {content["text"]}'), 2)
        transcription_table = document.add_table(rows=0, cols=2, style="Table Grid")
        row_cells = transcription_table.add_row().cells
        row_cells[0].text = safe_text("Pivot (if not English)")
        row_cells[1].text = safe_text("")
        row_cells = transcription_table.add_row().cells
        row_cells[0].text = safe_text(f'Sentence in {target_language}')
        row_cells[1].text = safe_text("")
        document.add_paragraph(safe_text(" "))
        p = document.add_paragraph()
        p.add_run(safe_text("Connections between word(s) and concept(s):")).bold = True
        document.add_paragraph(safe_text("In this segment, which word(s) contribute to which concept(s) below? One word can appear in multiple concepts, or in none. Multiple words can appear in a single concept."))
        concept_table = document.add_table(rows=1, cols=2, style="Table Grid")
        hdr_cells = concept_table.rows[0].cells
        hdr_cells[0].text = safe_text("Concept")
        hdr_cells[1].text = safe_text("Word(s) contributing to this concept")
        if content.get("intent", []) != []:
            row_cells = concept_table.add_row().cells
            row_cells[0].text = safe_text(f'Intent: {"+".join(content["intent"])}')
            row_cells[1].text = safe_text("")
        if content.get("predicate", []) != []:
            row_cells = concept_table.add_row().cells
            row_cells[0].text = safe_text(f'Type of predicate: {"+".join(content["predicate"])}')
            row_cells[1].text = safe_text("")
        for c in content["concept"]:
            row_cells = concept_table.add_row().cells
            row_cells[0].text = safe_text(c)
            row_cells[1].text = safe_text("")

    # Save to a BytesIO buffer instead of disk
    docx_buffer = BytesIO()
    document.save(docx_buffer)
    docx_buffer.seek(0)  # Reset buffer position

    return docx_buffer


def generate_docx_from_kg_index_list(kg, delimiters, kg_index_list):
    kg = normalize_user_strings(kg)
    delimiters = normalize_user_strings(delimiters)
    document = Document()
    document.add_heading(safe_text('Partial corpus'), 0)
    item_counter = 0
    for index in kg_index_list:
        item_counter += 1
        data = kg[index]
        gloss = build_super_gloss(kg, index, delimiters)
        document.add_paragraph(safe_text("""Entry {}""".format(item_counter)), style='List Bullet')
        pex = document.add_paragraph(safe_text(" "), "Normal")
        pex.add_run(safe_text(f'{data["recording_data"]["translation"]}'), style='Strong')
        document.add_paragraph(safe_text(f'{data["sentence_data"]["text"]}'), "Normal")
        document.add_paragraph(safe_text(f'''
        Intent: {", ".join(data["sentence_data"]["intent"])}
        Type of predicate: {", ".join(data["sentence_data"]["predicate"])}
        '''), "Normal")

        # Define the number of rows (one header + words) and columns
        num_words = len(gloss)
        table = document.add_table(rows=num_words + 1, cols=4, style="Light Shading Accent 1")  # Fixed column count

        # Populate header row
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = safe_text("")
        hdr_cells[1].text = safe_text("Concept")
        hdr_cells[2].text = safe_text("Internal Particularisation")
        hdr_cells[3].text = safe_text("Relational Particularisation")

        # Populate the table with data
        for i, w in enumerate(gloss, start=1):
            row_cells = table.rows[i].cells
            row_cells[0].text = safe_text(w["word"])
            row_cells[1].text = safe_text(w["concept"])
            row_cells[2].text = safe_text(w["internal particularization"])
            row_cells[3].text = safe_text(w["relational particularization"])
        document.add_paragraph(safe_text("""   """))

    # Save to a BytesIO buffer instead of disk
    docx_buffer = BytesIO()
    document.save(docx_buffer)
    docx_buffer.seek(0)  # Reset buffer position

    return docx_buffer
