// Writes the character class planWordSplits counts to choose the half of a
// split word a node stays on, as code-point ranges: src/domain/letterClasses.js.
// Run from plaid-umr: `node tools/letterClasses.mjs`.
//
// The count used to ask the runtime (`/[\p{L}\p{N}]/u`), so its answer moved
// with the browser's or node's Unicode version, and the same open could cut a
// node differently in two browsers. Marks count too: in Devanagari or Bengali a
// vowel sign is part of the letter it follows, and leaving it out made the half
// with fewer letters look longer.
//
// UNICODE is pinned, as in plaid-igt/tools/punctuationClasses.mjs. Moving it is
// a deliberate change: run this with a node whose `process.versions.unicode` is
// the new one, and set it here.

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const UNICODE = '16.0';
if (process.versions.unicode !== UNICODE) {
  console.error(
    `This node has Unicode ${process.versions.unicode}, and the tables are pinned to ${UNICODE}.`,
  );
  process.exit(1);
}

const ranges = (re) => {
  const out = [];
  for (let cp = 0; cp <= 0x10ffff; cp++) {
    if (!re.test(String.fromCodePoint(cp))) continue;
    const last = out[out.length - 1];
    if (last && last[1] === cp - 1) last[1] = cp;
    else out.push([cp, cp]);
  }
  return out;
};

const letters = ranges(/[\p{L}\p{M}\p{N}]/u);

const hex = (cp) => `0x${cp.toString(16).padStart(4, '0')}`;
const jsRanges = (rs) => rs.map(([a, b]) => `  [${hex(a)}, ${hex(b)}],`).join('\n');

writeFileSync(
  resolve('src/domain/letterClasses.js'),
  `// Generated by tools/letterClasses.mjs (Unicode ${UNICODE}). Do not edit.
// Inclusive code-point ranges, sorted.

/** \`/[\\p{L}\\p{M}\\p{N}]/u\`: letters, marks and digits. */
export const LETTER_MARK_OR_NUMBER = [
${jsRanges(letters)}
];

const inRanges = (ranges, c) => {
  const cp = c.codePointAt(0);
  if (cp === undefined) return false;
  let lo = 0;
  let hi = ranges.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (cp < ranges[mid][0]) hi = mid - 1;
    else if (cp > ranges[mid][1]) lo = mid + 1;
    else return true;
  }
  return false;
};

/** Is the first code point of \`c\` a letter, a mark or a digit? */
export const isLetterMarkOrNumber = (c) => inRanges(LETTER_MARK_OR_NUMBER, c);
`,
);
console.log(`${letters.length} letter, mark and number ranges`);
