name: Build and Deploy Docs

on:
  push:
    branches: [ master ]
    paths: [ 'plaid-core/docs/**', 'plaid-core/target/clients/**' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Asciidoctor and CodeRay
      run: gem install asciidoctor coderay
      
    - name: Build HTML
      run: |
        mkdir -p _site
        asciidoctor -o _site/index.html plaid-core/docs/index.adoc
        asciidoctor -o _site/manual.html plaid-core/docs/manual.adoc
        asciidoctor -o _site/dev.html plaid-core/docs/dev.adoc
        node plaid-core/docs/extract-api-docs.js
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
